// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's profile, roles, and restaurant. Useful to verify connectivity and identity.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile } = await sb.from("profiles").select("id, email, full_name, restaurant_id").eq("id", userId).maybeSingle();
    let restaurant = null;
    let roles = [];
    if (profile?.restaurant_id) {
      const { data: r } = await sb.from("restaurants").select("id, name, slug, plan, status").eq("id", profile.restaurant_id).maybeSingle();
      restaurant = r;
      const { data: rr } = await sb.from("user_roles").select("role").eq("user_id", userId).eq("restaurant_id", profile.restaurant_id);
      roles = (rr ?? []).map((x) => x.role);
    }
    const result = { user_id: userId, email: ctx.getUserEmail(), profile, restaurant, roles };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_orders_default = defineTool2({
  name: "list_orders",
  title: "List orders",
  description: "List recent orders for the signed-in user's restaurant. Optional filters by status and branch.",
  inputSchema: {
    status: z.enum(["pending", "preparing", "ready", "delivered", "paid", "cancelled"]).optional().describe("Optional order status filter."),
    branch_id: z.string().uuid().optional().describe("Optional branch UUID filter."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows (1-100, default 25).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, branch_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("orders").select(
      "id, order_number, status, payment_status, type, customer_name, subtotal, total, branch_id, table_id, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (branch_id) q = q.eq("branch_id", branch_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_order_default = defineTool3({
  name: "get_order",
  title: "Get order",
  description: "Fetch full details of a single order (including line items) by its UUID.",
  inputSchema: { order_id: z2.string().uuid().describe("Order UUID.") },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data: order, error } = await sb.from("orders").select("*").eq("id", order_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!order) return { content: [{ type: "text", text: "Order not found" }], isError: true };
    const { data: items } = await sb.from("order_items").select("id, product_name, quantity, unit_price, notes").eq("order_id", order_id);
    const result = { order, items: items ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_products_default = defineTool4({
  name: "list_products",
  title: "List menu products",
  description: "List menu products for the signed-in user's restaurant.",
  inputSchema: {
    category_id: z3.string().uuid().optional().describe("Optional category UUID."),
    available_only: z3.boolean().optional().describe("If true, return only available products. Default false.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ category_id, available_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let q = sb.from("products").select("id, name, description, price, available, category_id, image_url, sort_order").order("sort_order", { ascending: true });
    if (category_id) q = q.eq("category_id", category_id);
    if (available_only) q = q.eq("available", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_categories_default = defineTool5({
  name: "list_categories",
  title: "List menu categories",
  description: "List menu categories for the signed-in user's restaurant.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    const { data, error } = await sb.from("categories").select("id, name, description, sort_order, active").order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-branches.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_branches_default = defineTool6({
  name: "list_branches",
  title: "List branches",
  description: "List branches for the signed-in user's restaurant.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser6(ctx);
    const { data, error } = await sb.from("branches").select("id, name, address, phone, is_main, active").order("is_main", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { branches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-order-status.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_order_status_default = defineTool7({
  name: "update_order_status",
  title: "Update order status",
  description: "Update the workflow status of an order (pending, preparing, ready, delivered, paid, cancelled). Requires manager or higher role via RLS.",
  inputSchema: {
    order_id: z4.string().uuid().describe("Order UUID."),
    status: z4.enum(["pending", "preparing", "ready", "delivered", "paid", "cancelled"]).describe("New order status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser7(ctx);
    const { data, error } = await sb.from("orders").update({ status }).eq("id", order_id).select("id, order_number, status, payment_status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "Order not found or access denied" }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tozxaevzkqlrzxpyzmul";
var mcp_default = defineMcp({
  name: "restocloud-mcp",
  title: "RestoCloud MCP",
  version: "0.1.0",
  instructions: "Herramientas para consultar y operar un restaurante en RestoCloud (multitenant SaaS). Todas las llamadas se ejecutan como el usuario autenticado y respetan el aislamiento por restaurante y sucursal (RLS). Empez\xE1 con `whoami` para verificar la sesi\xF3n, luego us\xE1 `list_orders`, `list_products`, `list_categories`, `list_branches`, `get_order` para leer, y `update_order_status` para cambiar el estado de un pedido.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_orders_default,
    get_order_default,
    list_products_default,
    list_categories_default,
    list_branches_default,
    update_order_status_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
